$schema: http://json-schema.org/draft-04/schema#
type: object
additionalProperties: false
properties:
    stardis_config_version:
        enum:
        - 1.0
    atom_data:
        type: string
    model:
        type: object
        additionalProperties: false
        properties:
            type:
                enum:
                - marcs
            fname:
                type: string
            gzipped:
                type: boolean
                default: false            
            final_atomic_number:
                type: number
                multipleOf: 1
                default: 30

        required:
        - type
        - fname
    opacity:
        type: object
        additionalProperties: false
        properties:
            file:
                type: object
                default: {}
                additionalProperties: false
                patternProperties:
                    _bf$:
                        type: string
                    _ff$:
                        type: string
            bf:
                type: object
                default: {}
                additionalProperties:
                    type: object
                    additionalProperties: false
                    properties:
                        gaunt:
                            type: [string, "null"]
                            default: null
                        departure:
                            type: [string, "null"]
                            default: null
            ff:
                type: object
                default: {}
                additionalProperties:
                    type: object
                    additionalProperties: false
                    properties:
                        gaunt:
                            type: [string, "null"]
                            default: null
                        departure:
                            type: [string, "null"]
                            default: null
            rayleigh:
                type: array
                default: []
                items:
                    enum:
                    - H
                    - He
                    - H2
            disable_electron_scattering:
                type: boolean
                default: false
            line:
                type: object
                additionalProperties: false
                properties:
                    disable:
                        type: boolean
                        default: false
                    broadening:
                        type: array
                        items:
                            enum:
                            - linear_stark
                            - quadratic_stark
                            - van_der_waals
                            - radiation
                        default: []
                    min:
                        type: quantity
                        default: 0 Hz
                    max:
                        type: quantity
                        default: inf Hz
                    broadening_range:
                        type: [quantity, "null"]
                        default: null
        #required:
        #- line
    no_of_thetas:
        type: number
        multipleOf: 1
        default: 10
    result_options:
        type: object
        additionalProperties: False
        default: {}
        properties:
            return_model:
                type: boolean
                default: false
            return_plasma:
                type: boolean
                default: false
            return_radiation_field:
                type: boolean
                default: True
    required:
    - stardis_config_version
    - atom_data
    - model
    - opacity
