name: build-docs
on: push
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo-hello-world
        run: |
          echo "Hello World!"
          uname -a
          lsb_release -a

  build-sphinx-html:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: stardis
          use-mamba: true
      
      - name: Cache Environment Lockfile
        id: cache-env-lockfile
        uses: actions/cache@v3
        with:
          path: /usr/share/miniconda3/envs/stardis
          key: conda-linux-64-lockfile
                  
      - name: Update Conda Environment
        id: update-env
        run: |
          wget -nv https://github.com/tardis-sn/tardis/releases/latest/download/conda-linux-64.lock -O conda-linux-64.lock
          mamba update -n stardis --file conda-linux-64.lock
        if: steps.cache-env-lockfile.outputs.cache-hit != 'true'
        
      - name: Install TARDIS
        id: install-tardis
        run: |
          pip install git+https://github.com/tardis-sn/tardis.git@release-2023.04.16

      - name: Install STARDIS
        id: install-stardis
        run: |
          cd ..
          python setup.py develop
