name: tests

on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - '*'

env:
  CACHE_NUMBER: 0  # increase to reset cache manually
  PYTEST_FLAGS: --cov=stardis --cov-report=xml --cov-report=html
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    # if: github.repository_owner == 'tardis-sn'
    strategy:
      matrix:
        include:

        - os: ubuntu-latest
          label: linux-64
          prefix: /usr/share/miniconda3/envs/tardis

        - os: macos-latest
          label: osx-64
          prefix: /Users/runner/miniconda3/envs/tardis
    
    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: stardis
          use-mamba: true


